version: '3.8'

services:
  # 1. SERVIÇO DE BANCO DE DADOS (Ex: PostgreSQL)
  db:
    image: postgres:16-alpine # Usa uma imagem oficial
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: what-to-do-db
    ports:
      - "5433:5432" # Mapeia a porta do contêiner para a sua máquina
    volumes:
      - ./postgres:/var/lib/postgresql/data # Persistência dos dados
    healthcheck: # Verifica se o DB está aceitando conexões
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. SERVIÇO DE BACKEND (NestJS)
  backend:
    build:
      context: ./backend # Indica onde procurar o Dockerfile do backend
    ports:
      - "3005:3005"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/gpx-storage:/usr/src/app/gpx-storage # Monta o diretório local para facilitar o desenvolvimento (hot-reload)
    depends_on:
      db:
        condition: service_healthy # Garante que o DB inicie antes do backend

    command: sh -c "mkdir -p /usr/src/app/gpx-storage && export DB_HOST=db && npm run start:dev"
    

    environment:
      DATABASE_HOST: db # A chave: usa o nome do serviço 'db' como hostname
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      DATABASE_NAME: what-to-do-db
      PORT: 3005
    

  # 3. SERVIÇO DE FRONTEND (React)
  frontend:
    build:
      context: ./frontend/what-to-do-front # Indica onde procurar o Dockerfile do frontend
    ports:
      - "5174:5174" # Acessível via http://localhost:80 (ou apenas http://localhost)
    volumes:
      - ./frontend/what-to-do-front:/app
    command: npm run dev
    environment:
      VITE_HOST: 0.0.0.0
    depends_on:
      - backend